language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
env:
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"
install:
  - pip install --upgrade -q pip setuptools
  - pip install -q $DJANGO
  - pip install -e .
script:
  - ./runtests.py
